### ISSUE TITLE
[BUG] Distorted internal speaker sound on sof-rt5682

### ISSUE THREAD

**Issue by micmalti** [thesofproject/sof#9219]
**Describe the bug**
I purchased a Chromebook Plus 515 with a 12th gen Intel CPU (i3-1215u) and decided to flash Coreboot (via [MrChromebox's firmware utility](https://docs.chrultrabook.com/docs/firmware/flashing-firmware.html)) to replace ChromeOS with a Linux distro, more specifically Manjaro. Seeing that the sound card wasn't being detected by the system, I ran [this script](https://github.com/WeirdTreeThing/chromebook-linux-audio/blob/main/setup-audio) and got it to work. However, while there aren't sound quality issues when using Bluetooth or jack-connected headphones, audio coming from the internal speakers [sounds garbled and choppy](https://drive.google.com/file/d/1bU_UF6Qy83NznR5K_PjlWeTW6ZBSOm_E/view?usp=sharing).

I'm able to confirm that this bug is experienced by at least one other user, so it probably isn't hardware-related, and it's not OS-related either, being also present on EndeavourOS. Switching from WirePlumber to PulseAudio did not resolve the issue. Using PulseAudio didn't help as well.

**To Reproduce**
This issue may just be limited to Chromebooks running Linux given their use of I2S codecs as opposed to HDA. For that matter, repeating the steps described above on a Chromebook with an sof-rt5682 sound card to install Linux and enable detection of the card will reproduce the issue.

**System information**

[dmesg.log](https://github.com/user-attachments/files/15789886/dmesg.log)

```
Audio:
  Device-1: Intel Alder Lake PCH-P High Definition Audio
    driver: sof-audio-pci-intel-tgl
    alternate: snd_hda_intel,snd_sof_pci_intel_tgl bus-ID: 00:1f.3
    chip-ID: 8086:51c8 class-ID: 0401
  API: ALSA v: k6.8.12-3-MANJARO status: kernel-api with: aoss
    type: oss-emulator tools: alsactl,alsamixer,amixer
  Server-1: PipeWire v: 1.0.7 status: active with: 1: wireplumber
    status: active 2: pw-jack type: plugin tools: pw-cat,pw-cli,wpctl
  Server-2: PulseAudio v: 17.0 status: active with: pulseaudio-alsa
    type: plugin tools: pacat,pactl,pavucontrol
```

The current kernel parameters in use are: 
```
rw quiet splash udev.log_priority=3 acpi_osi=Linux snd_hda_intel.power_save=0
```

An attempt was made to also include the firmware log with `sof-tools-2024.03-1`, yet the package version is seemingly incompatible with the current Linux version, returning an `Invalid ldc file signature` when executing:
`sudo sof-logger -l /sys/kernel/debug/sof/etrace -o sof-logger.log`

I'm not sure whether this is relevant, but the information reported by `alsamixer` doesn't match up with what's reported by the display controls. The following is for the headphone audio (the volume control for the internal speakers is missing):

![Image](https://forum.chrultrabook.com/uploads/default/original/1X/595cec380a19fd18c7ea12275092b61ee82be2cb.gif)
